function [ labels, chanlocs ] = antChannelLocs( input_args )
%ANTCHANNELLOCS Summary of this function goes here
%   Detailed explanation goes here

labels =            [{'Fp1'}, {'Fpz'}, {'Fp2'},...
{'F7'},      {'F3'},          {'Fz'},            {'F4'},      {'F8'}, ...
       {'FC5'},      {'FC1'},          {'FC2'},        {'FC6'}, ...
      {'M1'}, {'T7'}, {'C3'}, {'Cz'}, {'C4'}, {'T8'}, {'M2'}, ...
       {'CP5'},     {'CP1'},           {'CP2'},        {'CP6'}, ...
{'P7'},       {'P3'},         {'Pz'},            {'P4'},      {'P8'}, ...
                              {'POz'}, ...
                     {'O1'},  {'Oz'},  {'O2'}, ...
{'CPz'}, {'counter'}];

for i = 1:length(labels)
    EEG.chanlocs(i).labels = labels{i};
end
if(nargout > 1)    
    EEG = setStandardLocations(EEG);
end
chanlocs = EEG.chanlocs;

end

