function eeg = loadGhermanEeg(filename)

data = load(filename);
eeg = eeg_emptyset;
eeg.data = data.EEGdata.Y;
%eeg.srate = data.EEGdata.fs;
eeg.srate = data.fs;

allChans = readlocs('C:\Users\Neuro\Documents\MATLAB\data\GhermanPhilastides\1.0.1\additional_files_electrode_info.elp');

clear chanlocs;
chanCounter = 1;
for i = 1:length(data.EEGdata.chnan)
    if(~any(data.excludedchannels == i))
        %         chanloc.labels = sprintf('Ch%d', i);
        %         chanlocs(chanCounter) = chanloc;
        chanlocs(chanCounter) = allChans(i);
        chanCounter = chanCounter + 1;
        
    end
end
eeg.chanlocs = chanlocs;
%eeg = setStandardLocations(eeg);

eeg.nbchan = length(chanlocs);
eeg.pnts = size(eeg.data, 2);
eeg.times = (1:eeg.pnts) ./ eeg.srate;
[~, file, ext] = fileparts(filename);
eeg.filename = [file ext];
eeg.filepath = filename;

candidateLocs = [...
    {'Fp1' },...
    {'Fp2' },...
    {'F3'  },...
    {'F4'  },...
    {'C3'  },...
    {'C4'  },...
    {'P3'  },...
    {'P4'  },...
    {'O1'  },...
    {'O2'  },...
    {'F7'  },...
    {'F8'  },...
    {'T7'  },...
    {'T8'  },...
    {'P7'  },...
    {'P8'  },...
    {'Fz'  },...
    {'Cz'  },...
    {'Pz'  },...
    {'Oz'  },...
    {'FC1' },...
    {'FC2' },...
    {'CP1' },...
    {'CP2' },...
    {'FC5' },...
    {'FC6' },...
    {'CP5' },...
    {'CP6' },...
    {'TP9' },...
    {'TP10'},...
    {'POz' },...
    {'F1'  },...
    {'F2'  },...
    {'C1'  },...
    {'C2'  },...
    {'P1'  },...
    {'P2'  },...
    {'AF3' },...
    {'AF4' },...
    {'FC3' },...
    {'FC4' },...
    {'CP3' },...
    {'CP4' },...
    {'PO3' },...
    {'PO4' },...
    {'F5'  },...
    {'F6'  },...
    {'C5'  },...
    {'C6'  },...
    {'P5'  },...
    {'P6'  },...
    {'AF7' },...
    {'AF8' },...
    {'FT7' },...
    {'FT8' },...
    {'TP7' },...
    {'TP8' },...
    {'PO7' },...
    {'PO8' },...
    {'FT9' },...
    {'FT10'},...
    {'Fpz' },...
    {'CPz' }...
    ];