folder = 'C:\Users\Neuro\Downloads\psychTests\psychTests';
load(fullfile(folder, 'neuropsych.mat'));

timeFilters = {'_POST_', '_6M_'};
isPost = cellfun(@length, strfind(masterTable.Properties.VariableNames, timeFilters{1})) > 0;
preLabels = strrep(masterTable.Properties.VariableNames(isPost), '_POST', '');
preLabels = strrep(preLabels, '_Post', '');
preLabels = strrep(preLabels, '_post', '');
for i = 1:length(preLabels)
    label = preLabels{i};
    if(strcmp(label(end-2:end), '_Po'))
        label(end-2:end) = [];
        preLabels{i} = label;
    end
end
preInd = NaN(size(preLabels));
for i = 1:length(preInd)
    ind = find(strcmp(masterTable.Properties.VariableNames, preLabels{i}));
    if(length(ind) > 0)
        preInd(i) = ind;
    end
end

counter = 1;
postInd = find(isPost);
if(~exist('changeTable', 'var'))
    changeTable = table();
    for i = 1:length(preInd)
        if(~isnan(preInd(i)))
            preLabel = masterTable.Properties.VariableNames{preInd(i)};
            postLabel = masterTable.Properties.VariableNames{postInd(i)};
            masterTable(:, {preLabel, postLabel})
            if(isnumeric(masterTable{:,postLabel}) && isnumeric(masterTable{:,preLabel}))
                newColumn = masterTable{:, postLabel} - masterTable{:, preLabel};
                newColumn(abs(newColumn) > 5000) = 0;
                changeTable{:, counter} = newColumn;
                changeTable.Properties.VariableNames{counter} = preLabel;
                counter = counter + 1;
            end
        end
    end
    
    
    tablePairs = [...
        {'BSI_csvBSI_1'                                           },{'Nervousness or shakiness inside'};...
        {'BSI_csvBSI_2'                                           },{'Faintness or dizziness'};...
        {'BSI_csvBSI_3'                                           },{'The idea that someone else can control your thoughts'};...
        {'BSI_csvBSI_4'                                           },{'Feeling others are to blame for most of your troubles'};...
        {'BSI_csvBSI_5'                                           },{'Trouble remembering things'};...
        {'BSI_csvBSI_6'                                           },{'Feeling esaily annoyed or irritated'};...
        {'BSI_csvBSI_7'                                           },{'Pains in heart or chest'};...
        {'BSI_csvBSI_8'                                           },{'Feeling afraid in open spaces or on the streets'};...
        {'BSI_csvBSI_9'                                           },{'Thoughts of ending your life'};...
        {'BSI_csvBSI_10'                                          },{'Feeling that most people cannot be trusted'};...
        {'BSI_csvBSI_11'                                          },{'Poor appetite'};...
        {'BSI_csvBSI_12'                                          },{'Suddenly scared for no reason'};...
        {'BSI_csvBSI_13'                                          },{'Temper outbursts that you could not control'};...
        {'BSI_csvBSI_14'                                          },{'Feeling lonely even when you are with people'};...
        {'BSI_csvBSI_15'                                          },{'Feeling blocked in getting things done'};...
        {'BSI_csvBSI_16'                                          },{'Feeling lonely'};...
        {'BSI_csvBSI_17'                                          },{'Feeling blue'};...
        {'BSI_csvBSI_18'                                          },{'Feeling no interest in things'};...
        {'BSI_csvBSI_19'                                          },{'Feeling fearful'};...
        {'BSI_csvBSI_20'                                          },{'Your feelings being easily hurt'};...
        {'BSI_csvBSI_21'                                          },{'Feeling tha tpeople are unfriendly or dislike you'};...
        {'BSI_csvBSI_22'                                          },{'Feeling inferior to others'};...
        {'BSI_csvBSI_23'                                          },{'Nausea or upset stomach'};...
        {'BSI_csvBS__24'                                          },{'Feeling that you are watched or talked about by others'};...
        {'BSI_csvBSI_25'                                          },{'Trouble falling asleep'};...
        {'BSI_csvBSI_26'                                          },{'Having to check and double-check what you do'};...
        {'BSI_csvBSI_27'                                          },{'Difficulty making decisions'};...
        {'BSI_csvBSI_28'                                          },{'Feeling afraid to travel on buses, subways, or trains'};...
        {'BSI_csvBSI_29'                                          },{'Trouble getting your breath'};...
        {'BSI_csvBSI_30'                                          },{'Hot or cold spells'};...
        {'BSI_csvBSI_31'                                          },{'Having to avoid certain things, places, or activities because they frighten you'};...
        {'BSI_csvBSI_32'                                          },{'Your mind going blank'};...
        {'BSI_csvBSI_33'                                          },{'Numbness or tinlging in parts of your body'};...
        {'BSI_csvBSI_34'                                          },{'The idea that you should be punished for your sins'};...
        {'BSI_csvBSI_35'                                          },{'Feeling hopeless about the future'};...
        {'BSI_csvBSI_36'                                          },{'Trouble concentrating'};...
        {'BSI_csvBSI_37'                                          },{'Feeling weak in parts of your body'};...
        {'BSI_csvBSI_38'                                          },{'Feeling tense or keyed up'};...
        {'BSI_csvBSI_39'                                          },{'Thoughts of death or dying'};...
        {'BSI_csvBSI_40'                                          },{'Having urges to beat, injure, or harm someone'};...
        {'BSI_csvBSI_41'                                          },{'Having urges to break or smash things'};...
        {'BSI_csvBSI_42'                                          },{'Feeling very self-conscious with others'};...
        {'BSI_csvBSI_43'                                          },{'Feeling uneasy in crowds, such as shopping or at a movie'};...
        {'BSI_csvBSI_44'                                          },{'Never feeling close to another person'};...
        {'BSI_csvBSI_45'                                          },{'Spells of terror or panic'};...
        {'BSI_csvBSI_46'                                          },{'Getting into frequent arguments'};...
        {'BSI_csvBSI_47'                                          },{'Feeling nervous when you are left alone'};...
        {'BSI_csvBSI_48'                                          },{'Others not giving you proper credit for your achievements'};...
        {'BSI_csvBSI_49'                                          },{'Feeling so restless you couldn''t sit still'};...
        {'BSI_csvBSI_50'                                          },{'Feelings of worthlessness'};...
        {'BSI_csvBSI_51'                                          },{'Feeling that people will take advantage of you if you let them'};...
        {'BSI_csvBSI_52'                                          },{'Feelings of guilt'};...
        {'BSI_csvBSI_53'                                          },{'The idea that something is wrong with your mind'};...
        {'BSI_csvBSI_SOM_A_sub'                                   },{''};...
        {'BSI_csvBSI_SOM_B_sub'                                   },{''};...
        {'BSI_csvBSI_SOM_A_Sum'                                   },{'Somatization scale'};...
        {'BSI_csvBSI_OC_A_sub'                                    },{''};...
        {'BSI_csvBSI_OC_B_sub'                                    },{''};...
        {'BSI_csvBSI_OC_A_Sum'                                    },{'Obsessive-compulsive scale'};...
        {'BSI_csvBSI_IS_A_sub'                                    },{''};...
        {'BSI_csvBSI_IS_B_sub'                                    },{''};...
        {'BSI_csvBSI_IS_A_Sum'                                    },{'Interpersonal Sensitivity scale'};...
        {'BSI_csvBSI_DEP_A_sub'                                   },{''};...
        {'BSI_csvBSI_DEP_B_sub'                                   },{''};...
        {'BSI_csvBSI_DEP_A_Sum'                                   },{'Depression scale'};...
        {'BSI_csvBSI_ANX_A_sub'                                   },{''};...
        {'BSI_csvBSI_ANX_B_sub'                                   },{''};...
        {'BSI_csvBSI_ANX_A_Sum'                                   },{'Anxiety scale'};...
        {'BSI_csvBSI_HOS_A_sub'                                   },{''};...
        {'BSI_csvBSI_HOS_B_sub'                                   },{''};...
        {'BSI_csvBSI_HOS_A_Sum'                                   },{'Hostility scale'};...
        {'BSI_csvBSI_PHOB_A_sub'                                  },{''};...
        {'BSI_csvBSI_PHOB_B_sub'                                  },{''};...
        {'BSI_csvBSI_PHOB_A_Sum'                                  },{'Phobic anxiety scale'};...
        {'BSI_csvBSI_PAR_A_sub'                                   },{''};...
        {'BSI_csvBSI_PAR_B_sub'                                   },{''};...
        {'BSI_csvBSI_PAR_A_Sum'                                   },{'Paranoid ideation scale'};...
        {'BSI_csvBSI_PSY_A_sub'                                   },{''};...
        {'BSI_csvBSI_PSY_B_sub'                                   },{''};...
        {'BSI_csvBSI_PSY_A_Sum'                                   },{'Psychoticism scale'};...
        {'BSI_csvBSI_Additional_Sum'                              },{'Additional items'};...
        {'BSI_csvBSI_2_Total_Sum'                                 },{'Total sum'};...
        {'BSI_csvBSI_2_Total_Responses'                           },{'Total number of positive responses'};...
        {'BSI_csvBSI_2_Raw_GSI'                                   },{'Raw Global Severity Index'};...
        {'BSI_csvBSI_3_Raw_PST'                                   },{''};...
        {'BSI_csvBSI_4_Total_Sum'                                 },{''};...
        {'BSI_csvBSI_4_Nonzero'                                   },{''};...
        {'BSI_csvBSI_4_Raw_PSDI'                                  },{''};...
        {'BSI_csvBSI_SOM_Raw'                                     },{'Somatization raw score'};...
        {'BSI_csvBSI_OC_Raw'                                      },{'Obsessive-compulsve raw score'};...
        {'BSI_csvBSI_IS_Raw'                                      },{'Interpersonal sensitivity raw score'};...
        {'BSI_csvBSI_DEP_Raw'                                     },{'Depression raw score'};...
        {'BSI_csvBSI_ANX_Raw'                                     },{'Anxiety raw score'};...
        {'BSI_csvBSI_HOS_Raw'                                     },{'Hositility raw score'};...
        {'BSI_csvBSI_PHOB_Raw'                                    },{'Phobic anxiety raw score'};...
        {'BSI_csvBSI_PAR_Raw'                                     },{'Paranoid ideation raw score'};...
        {'BSI_csvBSI_PSY_Raw'                                     },{'Psychoticism raw score'};...
        {'BSI_csvBSI_GSI_Raw'                                     },{'Global Severity Index raw score'};...
        {'BSI_csvBSI_PSDI_Raw'                                    },{''};...
        {'BSI_csvBSI_PST_Raw'                                     },{''};...
        {'BSI_csvBSI_SOM_T_Score'                                 },{'Somatization T-score'};...
        {'BSI_csvBSI_OC_T_Score'                                  },{'Obsessive-compulsive T-score'};...
        {'BSI_csvBSI_IS_T_Score'                                  },{'Interpersonal sensitivity T-score'};...
        {'BSI_csvBSI_DEP_T_Score'                                 },{'Depression T-score'};...
        {'BSI_csvBSI_ANX_T_Score'                                 },{'Anxiety T-score'};...
        {'BSI_csvBSI_HOS_T_Score'                                 },{'Hostility T-score'};...
        {'BSI_csvBSI_PHOB_T_Score'                                },{'Phobic anxiety T-score'};...
        {'BSI_csvBSI_PAR_T_Score'                                 },{'Paranoid ideation T-score'};...
        {'BSI_csvBSI_PSY_T_Score'                                 },{'Psychoticism T-score'};...
        {'BSI_csvBSI_GSI_T_Score'                                 },{'Global Severity Index T-score'};...
        {'BSI_csvBSI_PSDI_T_Score'                                },{'Positive Symptom Distress Index T-score'};...
        {'BSI_csvBSI_PST_T_Score'                                 },{'Positive Symptom Total T-score'};...
        {'CSSRS_csvCSSRS_Ideation_1a'                             },{'Wish to be dead lifetime'};...
        {'CSSRS_csvCSSRS_Ideation_1b'                             },{'Wish to be dead past 1 month'};...
        {'CSSRS_csvCSSRS_Ideation_2a'                             },{'Non-specific active suicidal thoughts lifetime'};...
        {'CSSRS_csvCSSRS_Ideation_2b'                             },{'Non-specific active suicidal thoughts 1 month'};...
        {'CSSRS_csvCSSRS_Ideation_3a'                             },{'Suicidal ideation with method lifetime'};...
        {'CSSRS_csvCSSRS_Ideation_3b'                             },{'Suicidal ideation with method 1 month'};...
        {'CSSRS_csvCSSRS_Ideation_4a'                             },{'Suicidal ideation with intent lifetime'};...
        {'CSSRS_csvCSSRS_Ideation_4b'                             },{'Suicidal ideation with intent 1 month'};...
        {'CSSRS_csvCSSRS_Ideation_5a'                             },{'Suicidal ideation with plan lifetime'};...
        {'CSSRS_csvCSSRS_Ideation_5b'                             },{'Suicidal ideation with plan 1 month'};...
        {'CSSRS_csvCSSRS_Intensity_a_type'                        },{'Most severe ideation lifetime'};...
        {'CSSRS_csvCSSRS_Intensity_b_type'                        },{'Most severe ideation 1 month'};...
        {'CSSRS_csvCSSRS_Intensity_1a'                            },{'Ideation Frequency lifetime'};...
        {'CSSRS_csvCSSRS_Intensity_1b'                            },{'Ideation Frequency 1 month'};...
        {'CSSRS_csvCSSRS_Intensity_2a'                            },{'Ideation Duration lifetime'};...
        {'CSSRS_csvCSSRS_Intensity_2b'                            },{'Ideation Duration 1 month'};...
        {'CSSRS_csvCSSRS_Intensity_3a'                            },{'Ideation Controllability lifetime'};...
        {'CSSRS_csvCSSRS_Intensity_3b'                            },{'Ideation Controllability 1 month'};...
        {'CSSRS_csvCSSRS_Intensity_4a'                            },{'Ideation Deterrents lifetime'};...
        {'CSSRS_csvCSSRS_Intensity_4b'                            },{'Ideation Deterrents 1 month'};...
        {'CSSRS_csvCSSRS_Intensity_5a'                            },{'Ideation Reasons lifetime'};...
        {'CSSRS_csvCSSRS_Intensity_5b'                            },{'Ideation Reasons 1 month'};...
        {'CSSRS_csvCSSRS_Behavior_Actual_1a'                      },{''};...
        {'CSSRS_csvCSSRS_Behavior_Actual_1b'                      },{''};...
        {'CSSRS_csvCSSRS_Behavior_Actual_2a'                      },{'Number of suicide attempts lifetime'};...
        {'CSSRS_csvCSSRS_Behavior_Actual_2b'                      },{'Number of suicide attempts 1 month'};...
        {'CSSRS_csvCSSRS_Behavior_3a'                             },{'Non-suicidal self-injurious behavior lifetime'};...
        {'CSSRS_csvCSSRS_Behavior_3b'                             },{'Non-suicidal self-injurious behavior 1 month'};...
        {'CSSRS_csvCSSRS_Behavior_Interrupted_1a'                 },{''};...
        {'CSSRS_csvCSSRS_Behavior_Interrupted_1b'                 },{''};...
        {'CSSRS_csvCSSRS_Behavior_Interrupted_2a'                 },{'Number of interrupted attempts lifetime'};...
        {'CSSRS_csvCSSRS_Behavior_Interrupted_2b'                 },{'Number of interrupted attempts 1 month'};...
        {'CSSRS_csvCSSRS_Behavior_Aborted_1a'                     },{''};...
        {'CSSRS_csvCSSRS_Behavior_Aborted_1b'                     },{''};...
        {'CSSRS_csvCSSRS_Behavior_Aborted_2a'                     },{'Number of aborted attempts lifetime'};...
        {'CSSRS_csvCSSRS_Behavior_Aborted_2b'                     },{'Number of aborted attempts 1 month'};...
        {'CSSRS_csvCSSRS_Behavior_Preparatory_1a'                 },{''};...
        {'CSSRS_csvCSSRS_Behavior_Preparatory_1b'                 },{''};...
        {'CSSRS_csvCSSRS_Behavior_Preparatory_2a'                 },{'Number of preparatory acts lifetime'};...
        {'CSSRS_csvCSSRS_Behavior_Preparatory_2b'                 },{'Number of preparatory acts 1 month'};...
        {'CSSRS_csvCSSRS_Lethality_Actual_3a'                     },{'Actual Lethality'};...
        {'CSSRS_csvCSSRS_Lethality_Actual_1b'                     },{'Actual Lethality most recent'};...
        {'CSSRS_csvCSSRS_Lethality_Actual_2b'                     },{'Actual Lethality most lethal'};...
        {'CSSRS_csvCSSRS_Lethality_Actual_3b'                     },{'Actual Lethality initial attempt'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_1'                     },{'Able to obey simple commands or say any words'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_2a'                    },{'Is the assistance of another person at home essential for some activities of daily living'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_2b'                    },{'Do they need frequent help or someone to be around most of the time'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_2c'                    },{'Was assistance at home essential before the injury'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_3a'                    },{'Are they able to shop without assistance'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_3b'                    },{'Were they able to shop without assistance before the injury'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_4a'                    },{'Are they able to travel locally without assistance'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_4b'                    },{'Were they able to travel without assistance before the injury'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_5a'                    },{'Are they currently able to work to their previous capacity'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_5b'                    },{'How restricted is work capacity'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_5c'                    },{'Were they working or seeking employment before the injury'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_6a'                    },{'Are they able to resume regular social and leisure activities outside the home'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_6b'                    },{'What is the extent of restriction on social activities'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_6c'                    },{'Did they engage in regular social activites outside home before the injury'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_7a'                    },{'Have there been psychological problems resulting in ongoing family disruption or disruption to friendships'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_7b'                    },{'What has been the extent of disruption to family or friendships'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_7c'                    },{'Were there problems with family or friends before the injury'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_8a'                    },{'Are there other current problems'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_8b'                    },{'Were there similar problems before the injury'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_Epilepsy_1'            },{'Any seizures since injury'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_Epilepsy_2'            },{'Are they told they are at risk of seizures'};...
        {'Glasgow_Outcome_Scale_csvGlasgow_Scoring'               },{'GOSE Global Disability Index'};...
        {'Multilingual_Aphasia_csvMultilingual_Aphasia_First'     },{'Controlled Oral Word Association 1st trial'};...
        {'Multilingual_Aphasia_csvMultilingual_Aphasia_Second'    },{'Controlled Oral Word Association 2nd trial'};...
        {'Multilingual_Aphasia_csvMultilingual_Aphasia_Third'     },{'Controlled Oral Word Association 3rd trial'};...
        {'Multilingual_Aphasia_csvMultilingual_Aphasia_Total'     },{'Controlled Oral Word Association total raw score'};...
        {'Multilingual_Aphasia_csvMultilingual_Aphasia_Adjustment'},{'Controlled Oral Word Association age/education adjustment'};...
        {'Multilingual_Aphasia_csvMultilingual_Aphasia_Adjusted'  },{'Controlled Oral Word Association total adjusted score'};...
        {'Multilingual_Aphasia_csvMultilingual_Aphasia_Percentile'},{'Controlled Oral Word Association percentile rank'};...
        {'PCL_5_csvPCL5_c'                                        },{'PCL criterion C'};...
        {'PCL_5_csvPCL5_d'                                        },{'PCL criterion D'};...
        {'PCL_5_csvPCL5_d_additional1'                            },{''};...
        {'PCL_5_csvPCL5_d_additional2'                            },{''};...
        {'PCL_5_csvPCL5_d_additional3'                            },{''};...
        {'PCL_5_csvPCL5_e'                                        },{'PCL criterion E'};...
        {'PCL_5_csvPCL5_1'                                        },{'Repeated disturbing and unwanted memories of the experience'};...
        {'PCL_5_csvPCL5_2'                                        },{'Repeated disturbing dreams of the stressful experience'};...
        {'PCL_5_csvPCL5_3'                                        },{'Suddenly feeling or acting as if the stressfully experience were actually happening again'};...
        {'PCL_5_csvPCL5_4'                                        },{'Feeling very upset when something reminded you of the stressful experience'};...
        {'PCL_5_csvPCL5_5'                                        },{'Having strong physical reactions when something reminded you of the stressful experience'};...
        {'PCL_5_csvPCL5_6'                                        },{'Avoiding memories, thoughts or feelings related to the experience'};...
        {'PCL_5_csvPCL5_7'                                        },{'Avoiding external reminders of the experience'};...
        {'PCL_5_csvPCL5_8'                                        },{'Trouble remembering important parts of the experience'};...
        {'PCL_5_csvPCL5_9'                                        },{'Having strong negative beliefs about yourself, other people, or the world'};...
        {'PCL_5_csvPCL5_10'                                       },{'Blaming yourself or someone else for the experience or what happened after'};...
        {'PCL_5_csvPCL5_11'                                       },{'Having strong negative feelings such as fear, horror, anger, guilt, or shame'};...
        {'PCL_5_csvPCL5_12'                                       },{'Loss of interest in activites that you used to enjoy'};...
        {'PCL_5_csvPCL5_13'                                       },{'Feeling distant or cut off from other people'};...
        {'PCL_5_csvPCL5_14'                                       },{'Trouble experiencing positive feelings'};...
        {'PCL_5_csvPCL5_15'                                       },{'Irritable behavior, angry outbursts, or activing aggressively'};...
        {'PCL_5_csvPCL5_16'                                       },{'Taking too many risks or doing things that could cause harm'};...
        {'PCL_5_csvPCL5_17'                                       },{'Being superalert or watchful or on guard'};...
        {'PCL_5_csvPCL5_18'                                       },{'Feeling jumpy or easily startled'};...
        {'PCL_5_csvPCL5_19'                                       },{'Having difficulty concentrating'};...
        {'PCL_5_csvPCL5_20'                                       },{'Trouble falling or staying asleep'};...
        {'PSQI_csvPSQI_2'                                         },{'number of minutes it takes to fall asleep'};...
        {'PSQI_csvPSQI_4'                                         },{'how many hours of sleep per night'};...
        {'PSQI_csvPSQI_5_a'                                       },{'how often can you not get to sleep within 30 minutes'};...
        {'PSQI_csvPSQI_5_b'                                       },{'how often do you wake up in the middle of the night or early morning'};...
        {'PSQI_csvPSQI_5_c'                                       },{'how often do you get up to use the bathroom'};...
        {'PSQI_csvPSQI_5_d'                                       },{'how often can you not breathe comfortably'};...
        {'PSQI_csvPSQI_5_e'                                       },{'how often do you cough or snore loudly'};...
        {'PSQI_csvPSQI_5_f'                                       },{'how often do you feel too cold'};...
        {'PSQI_csvPSQI_5_g'                                       },{'how often do you feel too hot'};...
        {'PSQI_csvPSQI_5_h'                                       },{'how often do you have bad dreams'};...
        {'PSQI_csvPSQI_5_i'                                       },{'how often do you have pain'};...
        {'PSQI_csvPSQI_5_j_1'                                     },{'how often do you wake up for other reasons'};...
        {'PSQI_csvPSQI_6'                                         },{'How would you rate your sleep quality overall over the past month'};...
        {'PSQI_csvPSQI_7'                                         },{'How often have you taken medicine to help you sleep'};...
        {'PSQI_csvPSQI_8'                                         },{'How often have you had trouble staying awake while driving, eating, or engaging in social activity'};...
        {'PSQI_csvPSQI_9'                                         },{'How much of a problem has it been for you to keep up enough enthusiasm to get things done'};...
        {'PSQI_csvPSQI_10'                                        },{'Do you have a bed partner or room mate'};...
        {'PSQI_csvPSQI_10_a'                                      },{'How often does your bed partner say you snore'};...
        {'PSQI_csvPSQI_10_b'                                      },{'How often does your bed partner say you have long pauses between breaths'};...
        {'PSQI_csvPSQI_10_c'                                      },{'How often does your bed partner say your legs twitch or jerk while you sleep'};...
        {'PSQI_csvPSQI_10_d'                                      },{'How often does your bed partner say you have periods of confusion or disorientation while you sleep'};...
        {'PSQI_csvPSQI_10_e_1'                                    },{'How often does your bed partner say you have other restlessness while you sleep'};...
        {'Rivermead_csvRivermead_a'                               },{'Headaches'};...
        {'Rivermead_csvRivermead_b'                               },{'Feelings of dizziness'};...
        {'Rivermead_csvRivermead_c'                               },{'Nausea and/or Vomiting'};...
        {'Rivermead_csvRivermead_d'                               },{'Noise Sensitivity, easily upset by loud noise'};...
        {'Rivermead_csvRivermead_e'                               },{'Sleep Disturbance'};...
        {'Rivermead_csvRivermead_f'                               },{'Fatigue, tiring more easily'};...
        {'Rivermead_csvRivermead_g'                               },{'Beeing irritable, easily angered'};...
        {'Rivermead_csvRivermead_h'                               },{'Feeling depressed or tearful'};...
        {'Rivermead_csvRivermead_i'                               },{'Feeling frustrated or impatient'};...
        {'Rivermead_csvRivermead_j'                               },{'Forgetfulness, poor memory'};...
        {'Rivermead_csvRivermead_k'                               },{'Poor concentration'};...
        {'Rivermead_csvRivermead_l'                               },{'Taking longer to think'};...
        {'Rivermead_csvRivermead_m'                               },{'Blurred vision'};...
        {'Rivermead_csvRivermead_n'                               },{'Light sensitivity'};...
        {'Rivermead_csvRivermead_o'                               },{'double vision'};...
        {'Rivermead_csvRivermead_p'                               },{'restlessness'};...
        {'Rivermead_csvRivermead_q1_answer'                       },{'other difficulties (1)'};...
        {'Rivermead_csvRivermead_q2_answer'                       },{'other difficulties (2)'};...
        {'STROOP_csvSTROOP_T1_Responses'                          },{'Trial 1 responses'};...
        {'STROOP_csvSTROOP_T1_Correct'                            },{'Trial 1 correct'};...
        {'STROOP_csvSTROOP_T2_Responses'                          },{'Trial 2 responses'};...
        {'STROOP_csvSTROOP_T2_Correct'                            },{'Trial 2 correct'};...
        {'STROOP_csvSTROOP_T3_Responses'                          },{'Trial 3 responses'};...
        {'STROOP_csvSTROOP_T3_Correct'                            },{'Trial 3 correct'};...
        {'STROOP_csvSTROOP_W_Raw'                                 },{'Word score Raw'};...
        {'STROOP_csvSTROOP_W_Predicted'                           },{'Word score Predicted'};...
        {'STROOP_csvSTROOP_W_Residual'                            },{'Word score Residual'};...
        {'STROOP_csvSTROOP_W_Tscore'                              },{'Word T-score'};...
        {'STROOP_csvSTROOP_C_Raw'                                 },{'Color score Raw'};...
        {'STROOP_csvSTROOP_C_Predicted'                           },{'Color score Predicted'};...
        {'STROOP_csvSTROOP_C_Residual'                            },{'Color score Residual'};...
        {'STROOP_csvSTROOP_C_Tscore'                              },{'Color T-score'};...
        {'STROOP_csvSTROOP_CW_Raw'                                },{'Color-word score Raw'};...
        {'STROOP_csvSTROOP_CW_Predicted'                          },{'Color-word score Predicted'};...
        {'STROOP_csvSTROOP_CW_Residual'                           },{'Color-word score Residual'};...
        {'STROOP_csvSTROOP_CW_Tscore'                             },{'Color-word T-score'};...
        {'STROOP_csvSTROOP_Int_Raw'                               },{'Interference Raw'};...
        {'STROOP_csvSTROOP_Int_Predicted'                         },{'Interference Predicted'};...
        {'STROOP_csvSTROOP_Int_Residual'                          },{'Interference Residual'};...
        {'STROOP_csvSTROOP_Int_Tscore'                            },{'Interference T-score'};...
        {'Trail_Making_csvTrail_Errors_A'                         },{'Trail making test A errors'};...
        {'Trail_Making_csvTrail_Errors_B'                         },{'Trail making test B errors'};...
        {'WAIS_IV_csvWAIS_Test_Age_year'                          },{''};...
        {'WAIS_IV_csvWAIS_Test_Age_month'                         },{''};...
        {'WAIS_IV_csvWAIS_Test_Age_day'                           },{''};...
        {'WAIS_IV_csvWAIS_Digit_Raw'                              },{'WAIS digit span raw'};...
        {'WAIS_IV_csvWAIS_Digit_Scaled'                           },{'WAIS digit span scaled'};...
        {'WAIS_IV_csvWAIS_Symbol_Raw'                             },{'WAIS symbol search raw'};...
        {'WAIS_IV_csvWAIS_Symbol_Scaled'                          },{'WAIS symbol search scaled'};...
        {'WAIS_IV_csvWAIS_Coding_Raw'                             },{'WAIS symbol coding raw'};...
        {'WAIS_IV_csvWAIS_Coding_Scaled'                          },{'WAIS symbol coding scaled'};...
        {'WHODAS_csvWHODAS_F5'                                    },{'Living situation at time of interview'};...
        {'WHODAS_csvWHODAS_A1'                                    },{'Sex'};...
        {'WHODAS_csvWHODAS_A2'                                    },{'Age'};...
        {'WHODAS_csvWHODAS_A3'                                    },{'Years of education'};...
        {'WHODAS_csvWHODAS_A4'                                    },{'Marital status'};...
        {'WHODAS_csvWHODAS_A5'                                    },{'Employment status'};...
        {'WHODAS_csvWHODAS_D1_1'                                  },{'Concentrating on doing something for ten minutes'};...
        {'WHODAS_csvWHODAS_D1_2'                                  },{'Remembering to do important things'};...
        {'WHODAS_csvWHODAS_D1_3'                                  },{'Analyzing and finding solutions to problems in day-to-day life'};...
        {'WHODAS_csvWHODAS_D1_4'                                  },{'Learning a new task'};...
        {'WHODAS_csvWHODAS_D1_5'                                  },{'Generally understanding what people say'};...
        {'WHODAS_csvWHODAS_D1_6'                                  },{'Starting and maintaining a conversation'};...
        {'WHODAS_csvWHODAS_D2_1'                                  },{'Standing for long periods such as 30 minutes'};...
        {'WHODAS_csvWHODAS_D2_2'                                  },{'Standing up from sitting down'};...
        {'WHODAS_csvWHODAS_D2_3'                                  },{'Moving around inside your home'};...
        {'WHODAS_csvWHODAS_D2_4'                                  },{'Getting out of your home'};...
        {'WHODAS_csvWHODAS_D2_5'                                  },{'Walking a long distance such as a kilometer'};...
        {'WHODAS_csvWHODAS_D3_1'                                  },{'Washing your whole body'};...
        {'WHODAS_csvWHODAS_D3_2'                                  },{'Getting dressed'};...
        {'WHODAS_csvWHODAS_D3_3'                                  },{'Eating'};...
        {'WHODAS_csvWHODAS_D3_4'                                  },{'Staying by yourself for a few days'};...
        {'WHODAS_csvWHODAS_D4_1'                                  },{'Dealing with people you do not know'};...
        {'WHODAS_csvWHODAS_D4_2'                                  },{'Maintaining a friendship'};...
        {'WHODAS_csvWHODAS_D4_3'                                  },{'Getting along with people who are close to you'};...
        {'WHODAS_csvWHODAS_D4_4'                                  },{'Making new friends'};...
        {'WHODAS_csvWHODAS_D4_5'                                  },{'Sexual activities'};...
        {'WHODAS_csvWHODAS_D5_1'                                  },{'Taking care of household responsibilities'};...
        {'WHODAS_csvWHODAS_D5_2'                                  },{'Doing your most important tasks well'};...
        {'WHODAS_csvWHODAS_D5_3'                                  },{'Getting all the household work done that you needed to do'};...
        {'WHODAS_csvWHODAS_D5_4'                                  },{'Getting your household work done as quickly as needed'};...
        {'WHODAS_csvWHODAS_D5_01'                                 },{'How many of the past 30 days did you reduce or completely miss household work because of your health'};...
        {'WHODAS_csvWHODAS_D5_5'                                  },{'Your day-to-day work or school'};...
        {'WHODAS_csvWHODAS_D5_6'                                  },{'Doing your most important work/school tasks well'};...
        {'WHODAS_csvWHODAS_D5_7'                                  },{'Getting all the work done that you need to do'};...
        {'WHODAS_csvWHODAS_D5_8'                                  },{'Getting your work done as quickly as needed'};...
        {'WHODAS_csvWHODAS_D5_9'                                  },{'Working at a lower level'};...
        {'WHODAS_csvWHODAS_D5_10'                                 },{'Earning less money'};...
        {'WHODAS_csvWHODAS_D5_02'                                 },{'How many of the past 30 days did you miss work a half day or more because of health'};...
        {'WHODAS_csvWHODAS_D6_1'                                  },{'How much of a problem did you have in joinging in community activities'};...
        {'WHODAS_csvWHODAS_D6_2'                                  },{'How much of a problem did you have because of barriers or hindrances in the world around you'};...
        {'WHODAS_csvWHODAS_D6_3'                                  },{'How much of a problem did you have living with dignity because of the attitudes and actions of others'};...
        {'WHODAS_csvWHODAS_D6_4'                                  },{'How much time did you spend on your helath condition or its consequences'};...
        {'WHODAS_csvWHODAS_D6_5'                                  },{'How much have you been emotionally affected by your health'};...
        {'WHODAS_csvWHODAS_D6_6'                                  },{'How much has your health been a drain on the financial resources of you or your family'};...
        {'WHODAS_csvWHODAS_D6_7'                                  },{'How much of a problem did your family have because of your health problems'};...
        {'WHODAS_csvWHODAS_D6_8'                                  },{'How much of a problem did you have in doing things by yourself for relaxation or pleasure'};...
        {'WHODAS_csvWHODAS_H1'                                    },{'How many days in the past 30 were these difficulties present'};...
        {'WHODAS_csvWHODAS_H2'                                    },{'How many days in the past 30 were you totally unable to carry out your usual activities or work'};...
        {'WHODAS_csvWHODAS_H3'                                    },{'How many days in the past 30 did you cut back or reduce your usual activites'}];
    
    for i = 1:size(tablePairs, 1)
        ind = find(strcmp(changeTable.Properties.VariableNames, tablePairs{i,1}));
        changeTable.Properties.VariableDescriptions{ind} = tablePairs{i,2};
    end
end

%todo: predict changes in EEG using session 1 data

whoDasHeaders = {'WHODAS_csvWHODAS_D', ...
    'WHODAS_csvWHODAS_D1', ... 
    'WHODAS_csvWHODAS_D2', ... 
    'WHODAS_csvWHODAS_D3', ... 
    'WHODAS_csvWHODAS_D4', ...
    'WHODAS_csvWHODAS_D5', ... 
    'WHODAS_csvWHODAS_D6', ... 
    'PCL_5_csvPCL5', ... 
    'PSQI_csvPSQI_5', ... 
    'PSQI_csvPSQI_4', ... 
    'PSQI_csvPSQI_2', ... 
    'Rivermead_csvRivermead_',...
    'WAIS_IV_csvWAIS_Digit_',...
    'WAIS_IV_csvWAIS_Symbol_Raw',...
    'WAIS_IV_csvWAIS_Coding_Raw',...
    'BSI_csvBSI_PST_T_Score',...
    {'CSSRS_csvCSSRS_Ideation_1b', 'CSSRS_csvCSSRS_Ideation_2b', 'CSSRS_csvCSSRS_Ideation_3b', 'CSSRS_csvCSSRS_Ideation_4b', 'CSSRS_csvCSSRS_Ideation_5b'}...
    };
whoDasDescriptions = {'total', ...
    'cognition', ...
    'mobility', ...
    'self_care', ...
    'getting_along',...
    'life_activities', ...
    'work', ...
    'Pcl', ...
    'PSQI_bad', ...
    'hours_of_sleep', ...
    'sleep_latency', ...
    'tbi_symptoms',...
    'digit_span',...
    'symbol_search',...
    'symbol_coding',...
    'symptoms',...
    'suicidal_ideation' ...
    };
whoDasValence = {'bad', 'bad', 'bad', 'bad', 'bad', 'bad', 'bad', 'bad', };
whoTable = masterTable(:,1);
randomization = {'real', 'real', 'real', 'real', 'real', 'real', 'real', 'sham', 'sham', 'sham', 'sham', 'sham', 'real','real','real','sham','real', 'sham','sham','real','sham','n/a'}';
whoTable{:,2} = randomization;
whoTable.Properties.VariableNames{2} = 'randomization';

bsi = changeTable{:,1:53};
whoTable{:,3} = nansum(bsi, 2);
whoTable.Properties.VariableNames{3} = 'bsi';

column = 1;
for i = 1:length(whoDasHeaders)
    searchHeader = whoDasHeaders{i};
    if(ischar(searchHeader))
        isDisability = cellfun(@length, strfind(changeTable.Properties.VariableNames, searchHeader)) > 0;
    else
        %handle cells
        isDisability = false(1, length(changeTable.Properties.VariableNames));
        for j = 1:length(searchHeader)
            isDisability = isDisability | cellfun(@length, strfind(changeTable.Properties.VariableNames, searchHeader{j})) > 0;
        end
    end
    disabilityChange = changeTable{:,isDisability};
    removeColumn = all(isnan(disabilityChange), 1);
    disabilityChange(:, removeColumn) = [];
    removeRow = all(isnan(disabilityChange), 2);
    %     whoTable{:, i+3} = nansum(disabilityChange, 2);
    rowSums = nansum(disabilityChange, 2);
    group = whoTable{:,2};
    whoTable{:, i+3} = rowSums;
    
    group(removeRow) = [];
    rowSums(removeRow) = [];

    x1 = rowSums(strcmp(group,'real'));
    x2 = rowSums(strcmp(group,'sham'));
    [h(column,1), p(column,1)] = ttest2(x1,x2);
    d(column,1) = computeCohen_d(x2, x1);
    meanDiffs(column, 1) = mean(x2) - mean(x1);
    headers{column,1} = whoDasDescriptions{i};
    column = column + 1;
    whoTable.Properties.VariableNames{i+3} = whoDasDescriptions{i};
end
% remove = all(isnan(disabilityChange), 2);
% whoTable(remove, :)= [];
% % remove = all(whoTable{:, 3:end} == 0, 2);
% % whoTable(remove, :)= [];
% 
% for column = 3:size(whoTable,2)
%     x1 = whoTable{strcmp(whoTable{:,2},'real'),column};
%     x2 = whoTable{strcmp(whoTable{:,2},'sham'),column};
%     [h(column,1), p(column,1)] = ttest2(x1,x2);
%     d(column,1) = computeCohen_d(x1, x2);
%     headers{column,1} = whoTable.Properties.VariableNames{column};
% end

effectTable = table(headers, d, h, p, meanDiffs)
% 
% latencyHit = cellfun(@length, strfind(masterTable.Properties.VariableNames, 'PSQI_2')) > 0
%       masterTable.Properties.VariableNames(latencyHit)
% 
%  quickTab = masterTable(:,[{'PSQI_POST_csvPSQI_2_Post'}    {'PSQI_csvPSQI_2'}]);
%  quickTab(:,3) = randomization;
% 
