
inputFolder = '/Users/Geoff/Downloads/ROBI CVLT';
filter = 'expanded.txt';
files = dir(inputFolder);
targetInd = find(cellfun(@length, strfind({files.name}, filter)) > 0);

fileCounter = 1;

startTime = tic;
tab = table();

while(fileCounter <= length(targetInd))
    thisTime = toc(startTime);
    fprintf('\n(%f) file %d of %d', thisTime, fileCounter, length(targetInd));
    
    fileInd = targetInd(fileCounter);
    
    inputFile = 'ROBI022 base expanded.txt';
    inputFile = files(fileInd).name;
    inputFiles{fileCounter, 1} = inputFile;
    path = fullfile(inputFolder, inputFile);
    
    fileId = fopen(path, 'r');
    text = fscanf(fileId, '%c');
    
    fclose(fileId);
    
    columnLabels = {...
        ... %page 1
        ... %level of recall
        'immediate_recall_numberCorrect_trial1_raw',...
        'immediate_recall_numberCorrect_trial1_standard',...
        'immediate_recall_semanticClustering_trial1_raw',...
        'immediate_recall_semanticClustering_trial1_standard',...
        'immediate_recall_recallDiscriminability_trial1_raw',...
        'immediate_recall_recallDiscriminability_trial1_standard',...
        ...
        'immediate_recall_numberCorrect_trial2_raw',...
        'immediate_recall_numberCorrect_trial2_standard',...
        'immediate_recall_semanticClustering_trial2_raw',...
        'immediate_recall_semanticClustering_trial2_standard',...
        'immediate_recall_recallDiscriminability_trial2_raw',...
        'immediate_recall_recallDiscriminability_trial2_standard',...
        ...
        'immediate_recall_numberCorrect_trial3_raw',...
        'immediate_recall_numberCorrect_trial3_standard',...
        'immediate_recall_semanticClustering_trial3_raw',...
        'immediate_recall_semanticClustering_trial3_standard',...
        'immediate_recall_recallDiscriminability_trial3_raw',...
        'immediate_recall_recallDiscriminability_trial3_standard',...
        ...
        'immediate_recall_numberCorrect_trial4_raw',...
        'immediate_recall_numberCorrect_trial4_standard',...
        'immediate_recall_semanticClustering_trial4_raw',...
        'immediate_recall_semanticClustering_trial4_standard',...
        'immediate_recall_recallDiscriminability_trial4_raw',...
        'immediate_recall_recallDiscriminability_trial4_standard',...
        ...
        'immediate_recall_numberCorrect_trial5_raw',...
        'immediate_recall_numberCorrect_trial5_standard',...
        'immediate_recall_semanticClustering_trial5_raw',...
        'immediate_recall_semanticClustering_trial5_standard',...
        'immediate_recall_recallDiscriminability_trial5_raw',...
        'immediate_recall_recallDiscriminability_trial5_standard',...
        ...
        'immediate_recall_numberCorrect_allTrials_raw',...
        'immediate_recall_numberCorrect_allTrials_standard',...
        'immediate_recall_semanticClustering_allTrials_raw',...
        'immediate_recall_semanticClustering_allTrials_standard',...
        'immediate_recall_recallDiscriminability_allTrials_raw',...
        'immediate_recall_recallDiscriminability_allTrials_standard',...
        ...
        'immediate_recall_numberCorrect_trialB_raw',...
        'immediate_recall_numberCorrect_trialB_standard',...
        'immediate_recall_semanticClustering_trialB_raw',...
        'immediate_recall_semanticClustering_trialB_standard',...
        'immediate_recall_recallDiscriminability_trialB_raw',...
        'immediate_recall_recallDiscriminability_trialB_standard',...
        ...
        'shortDelay_freeRecall_numberCorrect_raw',...
        'shortDelay_freeRecall_numberCorrect_standard',...
        'shortDelay_freeRecall_semanticClustering_raw',...
        'shortDelay_freeRecall_semanticClustering_standard',...
        'shortDelay_freeRecall_recallDiscriminability_raw',...
        'shortDelay_freeRecall_recallDiscriminability_standard',...
        ...
        'shortDelay_cuedRecall_numberCorrect_raw',...
        'shortDelay_cuedRecall_numberCorrect_standard',...
        'shortDelay_cuedRecall_semanticClustering_raw',...
        'shortDelay_cuedRecall_semanticClustering_standard',...
        'shortDelay_cuedRecall_recallDiscriminability_raw',...
        'shortDelay_cuedRecall_recallDiscriminability_standard',...
        ...
        'longDelay_freeRecall_numberCorrect_raw',...
        'longDelay_freeRecall_numberCorrect_standard',...
        'longDelay_freeRecall_semanticClustering_raw',...
        'longDelay_freeRecall_semanticClustering_standard',...
        'longDelay_freeRecall_recallDiscriminability_raw',...
        'longDelay_freeRecall_recallDiscriminability_standard',...
        ...
        'longDelay_cuedRecall_numberCorrect_raw',...
        'longDelay_cuedRecall_numberCorrect_standard',...
        'longDelay_cuedRecall_semanticClustering_raw',...
        'longDelay_cuedRecall_semanticClustering_standard',...
        'longDelay_cuedRecall_recallDiscriminability_raw',...
        'longDelay_cuedRecall_recallDiscriminability_standard',...
        ... %page 2
        ... %learning characteristics
        'semanticClustering_raw',...
        'semanticClustering_standard',...
        'serialClustering_forward_raw',...
        'serialClustering_forward_standard',...
        'serialClustering_bidirectional_raw',...
        'serialClustering_bidirectional_standard',...
        'subjectiveClustering_bidirectional_raw',...
        'subjectiveClustering_bidirectional_standard',...
        'percentRecallFromPrimacy_raw',...
        'percentRecallFromPrimacy_standard',...
        'percentRecallFromMiddle_raw',...
        'percentRecallFromMiddle_standard',...
        'percentRecallFromRecency_raw',...
        'percentRecallFromRecency_standard',...
        'totalLearningSlope_raw',...
        'totalLearningSlope_standard',...
        'learningSlopeTrials1To2_raw',...
        'learningSlopeTrials1To2_standard',...
        'learningSlopeTrials2To5_raw',...
        'learningSlopeTrials2To5_standard',...
        'acorssTrialsRecallConsistency_raw',...
        'acorssTrialsRecallConsistency_standard',...
        ... %recall contrast measures
        'listB_vs_trial1_raw',...
        'listB_vs_trial1_standard',...
        'shortDelayFreeRecall_vs_trial5_raw',...
        'shortDelayFreeRecall_vs_trial5_standard',...
        'longDelayFreeRecall_vs_trial5_raw',...
        'longDelayFreeRecall_vs_trial5_standard',...
        'longDelayFreeRecall_vs_shortDelayFreeRecall_raw',...
        'longDelayFreeRecall_vs_shortDelayFreeRecall_standard',...
        ... %page 4
        ... %recall errors
        'totalRepetitions_raw',...
        'totalRepetitions_standard',...
        'totalIntrusions_raw',...
        'totalIntrusions_standard',...
        'total_immediateRecall_intrusions_raw',...
        'total_immediateRecall_intrusions_standard',...
        'total_delayedRecall_intrusions_raw',...
        'total_delayedRecall_intrusions_standard',...
        'total_freeRecall_intrusions_raw',...
        'total_freeRecall_intrusions_standard',...
        'total_cuedRecall_intrusions_raw',...
        'total_cuedRecall_intrusions_standard',...
        ...
        'total_nonCategory_intrusions_raw',...
        'total_nonCategory_intrusions_percentInAgeGroupWithThisScore',...
        'total_nonCategory_intrusions_percentInAgeGroupWithBetterScore',...
        'total_synonym_intrusions_raw',...
        'total_synonym_intrusions_percentInAgeGroupWithThisScore',...
        'total_synonym_intrusions_percentInAgeGroupWithBetterScore',...
        'total_acrossList_intrusions_raw',...
        'total_acrossList_intrusions_percentInAgeGroupWithThisScore',...
        'total_acrossList_intrusions_percentInAgeGroupWithBetterScore',...
        ...
        'totalRecallDiscriminability_raw',...
        'totalRecallDiscriminability_standard',...
        'immediateRecallDiscriminability_raw',...
        'immediateRecallDiscriminability_standard',...
        'delayedRecallDiscriminability_raw',...
        'delayedRecallDiscriminability_standard',...
        'freeRecallDiscriminability_raw',...
        'freeRecallDiscriminability_standard',...
        'cuedRecallDiscriminability_raw',...
        'cuedRecallDiscriminability_standard',...
        ... %page 5
        ... %delayed recognition
        'totalHits_raw',...
        'totalHits_standard',...
        'percentTotalAccuracy_raw',...
        'percentTotalAccuracy_percentInAgeGroupWithThisScore',...
        'percentTotalAccuracy_percentInAgeGroupWithBetterScore',...
        'totalFalsePositives_raw',...
        'totalFalsePositives_standard',...
        'percentConcreteAccuracy_raw',...
        'percentConcreteAccuracy_percentInAgeGroupWithThisScore',...
        'percentConcreteAccuracy_percentInAgeGroupWithBetterScore',...
        'totalRecognitionDiscriminability_raw',...
        'totalRecognitionDiscriminability_standard',...
        'percentAbstractAccuracy_raw',...
        'percentAbstractAccuracy_percentInAgeGroupWithThisScore',...
        'percentAbstractAccuracy_percentInAgeGroupWithBetterScore',...
        'sourceRecognitionDiscriminability_raw',...
        'sourceRecognitionDiscriminability_standard',...
        'semanticRecognitionDiscriminability_raw',...
        'semanticRecognitionDiscriminability_standard',...
        'novelRecognitionDiscriminability_raw',...
        'novelRecognitionDiscriminability_standard',...
        'totalResponseBias_raw',...
        'totalResponseBias_standard',...
        ... %delayed recognition
        'recogDiscrim_vs_longDelayFreeRecall_percentChange',...
        'recogDiscrim_vs_longDelayFreeRecall_ZScoreDifference',...
        'recogDiscrim_vs_longDelayFreeRecallDiscrim_percentChange',...
        'recogDiscrim_vs_longDelayFreeRecallDiscrim_ZScoreDifference',...
        ... %critical items: word count
        'recalledWordsNotForcedRecog_raw',...
        'recalledWordsNotForcedRecog_percentInAgeGroupWithThisScore',...
        'recalledWordsNotForcedRecog_percentInAgeGroupWithBetterScore',...
        'yesNoRecogWordsNotForcedRecog_raw',...
        'yesNoRecogWordsNotForcedRecog_percentInAgeGroupWithThisScore',...
        'yesNoRecogWordsNotForcedRecog_percentInAgeGroupWithBetterScore',...
        };
    
    newlines = strfind(text, sprintf('\n'));
    newlines = [0 newlines length(text)+1];
    firstDataStart = 'Trial 1';
    dataStarted = false;
    columnCounter = 1;
    parseTemplate = {...
        'Trial 1', (2:7),...
        'Trial 2', (2:7),...
        'Trial 3', (2:7),...
        'Trial 4', (2:7),...
        'Trial 5', (2:7),...
        'Trials 1-5 Total', (2:7),...
        'Trial B', (2:7),...
        'Short Delay Free Recall', (2:7),...
        'Short Delay Cued Recall', (2:7),...
        'Long Delay Free Recall', (2:7),...
        'Long Delay Cued Recall', (2:7),...
        'Semantic Clustering (Chance Adjusted)', (2:3),...
        'Serial Clustering Forward (Chance Adjusted)', (2:3),...
        'Serial Clustering Bidirectional (Chance Adjusted)', (2:3),...
        'Subjective Clustering Bidirectional (Chance Adjusted)', (2:3),...
        '% Recall from Primacy', (2:3),...
        '% Recall from Middle', (2:3),...
        '% Recall from Recency', (2:3),...
        'Total Learning Slope Trials 1-5', (2:3),...
        'Learning Slope Trials 1-2', (2:3),...
        'Learning Slope Trials 2-5', (2:3),...
        'Across-Trial Recall Consistency', (2:3),...
        'List B vs. Trial 1', (2:3),...
        'Short Delay Free Recall vs. Trial 5', (2:3),...
        'Long Delay Free Recall vs. Trial 5', (2:3),...
        'Long Delay Free Recall vs. Short Delay Free Recall', (2:3),...
        'Total Repetitions (All Recall Trials)', (2:3),...
        '"Total Intrusions (All Recall Trials, All Types)"', (3:4),...
        '"Total Immediate Recall Intrusions (Trials 1-5, All Types)"', (3:4),...
        '"Total Delayed Recall Intrusions (Free & Cued, All Types)"', (3:4),...
        '"Total Free Recall Intrusions (Immed. & Delayed, All Types)"', (3:4),...
        'Total Cued Recall Intrusions (All Types)', (2:3),...
        'Total Non-Category Intrusions (All Recall Trials)', (2:4),...
        'Total Synonym/Subordinate Intrusions (All Recall Trials)', (2:4),...
        'Total Across-List Intrusions (List B & Delayed Recall Trials)', (2:4),...
        '"Total Recall Discriminability (List A, All Trials vs. Total Intrusions)"', (3:4),...
        '"Immediate Recall Discriminability (List A, Trials 1-5 vs. Intrusions, Trials 1-5)"', (4:5),...
        '"Delayed Recall Discriminability (List A vs. Intrusions, Delayed Recall Trials)"', (3:4),...
        '"Free Recall Discriminability (List A vs. Intrusions, Immed. & Delayed Free Recall Trials) "', (3:4),...
        '"Cued Recall Discriminability (List A vs. Intrusions, Cued Recall Trials)"', (3:4),...
        'Total Hits,',[2:3, 5:7],...
        'Total False Positives', (2:3),...
        '% Concrete Accuracy (Hits [8]/8)*100 ', (2:4),...
        'Total Recognition Discriminability (d'') (Hits vs. Total False Positives) ', (2:3),...
        '% Abstract Accuracy (Hits [8]/8)*100 ', (2:4),...
        'Source Recognition Discriminability (d'') (Hits vs. List B False Positives [5]) ', (2:3),...
        'Semantic Recognition Discriminability (List A vs. List B Shared [0] & Prototypical [1] False Positives) ', (2:3),...
        'Novel Recognition Discriminability (d'') (Hits vs. Prototypical [1] & Unrelated [0] False Positives) ,', (2:3),...
        '"Total Response Bias (C)* * positive raw scores are in ''NO'' response-bias direction, negative raw scores are in the ''YES'' response-bias direction. "', (3:4),...
        'Total Recognition Discriminability vs. Long Delay Free Recall*', (2:3),...
        'Total Recognition Discriminability vs. Long Delay Free Recall Discriminability*', (2:3),...
        '"Number of target words recalled at least once, but missed on Forced Choice Recognition "', 3:5,...
        '"Number of target words that were Hits on Yes/No Recognition, but missed on Forced Choice Recognition "', 3:5,...
        
        
        };
    %    '', (3:4),...
    %
    %     'Short Delay Free Recall vs. Trial 5'
    
    parseTemplateCounter = 1;
    searchTarget = parseTemplate{parseTemplateCounter};
    itemDataIndex = parseTemplate{parseTemplateCounter+1};
    
    for i = 1:(length(newlines)-1)
        line = text(newlines(i)+1:newlines(i+1)-1);
        if(parseTemplateCounter == 91)
            dummy = 1;
        end
        if(length(strfind(line, searchTarget)) > 0)
            items = strsplit(line, ',');
            data = items(itemDataIndex);
            for j = 1:length(data)
                value = sscanf(data{j}, '%f');
                if(length(value) == 0)
                    value = NaN;
                end
                tab{fileCounter, columnCounter} = value;
                if(fileCounter == 1)
                    tab.Properties.VariableNames{columnCounter} = columnLabels{columnCounter};
                end
                columnCounter = columnCounter + 1;
            end
            parseTemplateCounter = parseTemplateCounter + 2;
            if(length(parseTemplate) > parseTemplateCounter)
                searchTarget = parseTemplate{parseTemplateCounter};
                itemDataIndex = parseTemplate{parseTemplateCounter+1};
            end
            
        end
    end
    
    fileCounter = fileCounter + 1;
end

tab2 = [table(inputFiles), tab]; 
